# Generated by Django 5.0.3 on 2024-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dtentry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
