# Generated by Django 5.0.3 on 2024-10-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ticket_dtentry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
