# Generated by Django 5.0.3 on 2024-10-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ticket_table_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
